// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var topLevels;
    topLevels = $('nav > ul > li');
    return $('nav > ul > li').click(function() {
      var _this = this;
      return $(topLevels).each(function(idx, it) {
        if (it === _this) {
          return $(_this).addClass('current');
        } else {
          return $(it).removeClass('current');
        }
      });
    });
  });

}).call(this);
