#!/bin/bash

./build

echo 'Building gallery.'

cd $(dirname $0)

THUMB_MAXSIZE=380x # width x height
LARGE_MAXSIZE=1000x

for f in content/galleria/*
do
	convert $f -resize $LARGE_MAXSIZE img/galleria/large/$(basename $f)
	convert $f -resize $THUMB_MAXSIZE img/galleria/thumb/$(basename $f)
done

php galleria/generate_html.php >> galleria/content.html

echo 'All done.'