#!/bin/bash

./build

echo 'Building gallery.'

cd $(dirname $0)

THUMB_MAXSIZE=380x # width x height

for f in content/galleria/*
do
	cp $f img/galleria/large/$(basename $f)
	convert $f -resize $THUMB_MAXSIZE img/galleria/thumb/$(basename $f)
done

php galleria/generate_html.php >> galleria/content.html

echo 'All done.'