#!/bin/sh

cd $(dirname $0)

THUMB_MAXSIZE=380x # width x height
LARGE_MAXSIZE=1000x

export PATH=$PATH:./node_modules/.bin

function ts() {
	date -u '+%Y-%m-%d %T.%3N'
}

echo `ts` Building.

lessc src/style.less > css/style.css
coffee -c -o js/ src/script.coffee 

pretext content/_.pre > content.html
for file in content/*.pre
do
	if [[ $file != content/_.pre ]]; then
		pretext $file > ./`basename $file .pre`/content.html
	fi
done

for ex in png
do
	for file in content/img/*.$ex
	do
		convert $file -resize $LARGE_MAXSIZE ./img/content/$(basename $file)
		convert $file -resize $THUMB_MAXSIZE ./img/content/$(basename $file .$ex)-thumb.$ex
	done
done

./build_gallery

echo `ts` Build finished.
