#!/bin/sh

cd $(dirname $0)

export PATH=$PATH:./node_modules/.bin

function ts() {
	date -u '+%Y-%m-%d %T.%3N'
}

echo `ts` Building.

lessc src/style.less > css/style.css
lessc src/style2.less > css/style2.css
coffee -c -o js/ src/script.coffee 

pretext content/_.pre > content.html
for file in content/*.pre
do
	if [[ $file != content/_.pre ]]; then
		pretext $file > ./`basename $file .pre`/content.html
	fi
done

echo `ts` Build finished.
